# Generated by Django 3.2.6 on 2022-04-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyJobMakerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
    ]
