# Generated by Django 4.0.3 on 2022-05-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyJobMakerApp', '0002_remove_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='in_progress',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
