# Generated by Django 4.0.3 on 2022-08-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyJobMakerApp', '0007_reviewrating_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='user',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='customer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='EasyJobMakerApp.customer'),
            preserve_default=False,
        ),
    ]
