# Generated by Django 4.0.3 on 2022-08-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyJobMakerApp', '0008_remove_reviewrating_user_reviewrating_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_provider',
            name='reviews_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service_provider',
            name='reviews_sum',
            field=models.IntegerField(default=0),
        ),
    ]
