# Generated by Django 4.0.3 on 2022-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyJobMakerApp', '0009_service_provider_reviews_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider',
            name='reviews_sum',
            field=models.FloatField(default=0),
        ),
    ]
