# Generated by Django 4.0.3 on 2022-08-15 16:34

import EasyJobMakerApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyJobMakerApp', '0010_alter_service_provider_reviews_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[(EasyJobMakerApp.models.Job_Application.Application_status['Pending'], 'PE'), (EasyJobMakerApp.models.Job_Application.Application_status['Accepted'], 'AC'), (EasyJobMakerApp.models.Job_Application.Application_status['Rejected'], 'RE')], default=EasyJobMakerApp.models.Job_Application.Application_status['Pending'], max_length=2)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyJobMakerApp.job')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyJobMakerApp.service_provider')),
            ],
        ),
    ]
