# Generated by Django 4.0.3 on 2022-08-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyJobMakerApp', '0012_job_application_service_provider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_application',
            name='service_provider_image',
        ),
        migrations.AddField(
            model_name='service_provider',
            name='customer',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='EasyJobMakerApp.customer'),
            preserve_default=False,
        ),
    ]
